// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUegr3wFcabdAl0wgwf23P3Sfws9F0glU',
    appId: '1:415302518477:web:967273d6abfdc29ca44b84',
    messagingSenderId: '415302518477',
    projectId: 'mainproject-6f254',
    authDomain: 'mainproject-6f254.firebaseapp.com',
    storageBucket: 'mainproject-6f254.appspot.com',
    measurementId: 'G-GF0FG9MHM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz0ytcSoY6eEZBYoolB8c5CCcn8QQO3xc',
    appId: '1:415302518477:android:fa3ce36c1a6c1c9ca44b84',
    messagingSenderId: '415302518477',
    projectId: 'mainproject-6f254',
    storageBucket: 'mainproject-6f254.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA14GRleB-eJpSJN24OgEHqq9ux02sCTt0',
    appId: '1:415302518477:ios:ec05f70095e721eaa44b84',
    messagingSenderId: '415302518477',
    projectId: 'mainproject-6f254',
    storageBucket: 'mainproject-6f254.appspot.com',
    iosBundleId: 'com.example.statemanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA14GRleB-eJpSJN24OgEHqq9ux02sCTt0',
    appId: '1:415302518477:ios:8628d1897c148c0da44b84',
    messagingSenderId: '415302518477',
    projectId: 'mainproject-6f254',
    storageBucket: 'mainproject-6f254.appspot.com',
    iosBundleId: 'com.example.statemanagement.RunnerTests',
  );
}
